### ISSUE TITLE
Map synthetic internal locations.

### ISSUE THREAD

**Issue by pacoporro** [Dynatrace/Dynatrace-Config-Manager#111]
It would be good to have the option to map internal synthetic locations from source to target, something like the users csv but for locations, so you can assign synthetic http and browsers to a new locations.

**Comment by dcryans** [comment]
Did you not name them exactly the same in both environments?
Then the entity matching will take care of it

**Comment by pacoporro** [comment]
That's the point 
During a phased migration we have duplicated the synthetic locations, they will not be located in the same places with the same names.

**Comment by dcryans** [comment]
I can provide a way to manually map any entity ID to any entity ID, as long as it's the same type of course

So you could provide multiple csv file, which would contain any mapping you would like to change:
SYNTHETIC_LOCATION-AAA,SYNTHETIC_LOCATION-BBB
SERVICE-AAA,SERVICE-BBB

Would that work for you?

**Comment by pacoporro** [comment]
Yes, that will be amazing.

**Comment by dcryans** [comment]
Here: https://github.com/Dynatrace/Dynatrace-Config-Manager/releases/latest
