### ISSUE TITLE
Management zone not included in alerting profile after migrating configs

### ISSUE THREAD

**Issue by sanitec** [Dynatrace/Dynatrace-Config-Manager#115]
**Describe the bug**
We see that the management zone field is not being mapped during the creation of Alerting Profiles.

This seem to work just fine for other configuration items that have mapped MZ to it's settings. Such as Metric Events and Dashboards.

Is this trivial to fix?

**Comment by dcryans** [comment]
I will now use both V1 and V2 IDs for MZ dependencies in every config where we were using V1
This will future proof the dependency code

**Comment by dcryans** [comment]
Fixed in latest release:
https://github.com/Dynatrace/Dynatrace-Config-Manager/releases/latest

Thank you for flagging the issue
