### ISSUE TITLE
AWS Credentials missing

### ISSUE THREAD

**Issue by sanitec** [Dynatrace/Dynatrace-Config-Manager#118]
**Describe the bug**
We discovered that the latest run with the config manager no longer pushes AWS Credentials. It worked on a previous version of the tool.

Has there been any change related to AWS Credentials?

**Comment by dcryans** [comment]
I'm adding more error logs for the next version
aws_credentials will also be fixed

The terraform provider has been updated multiple times for aws_credentials specific problems
One of the changes broke the export

**Comment by dcryans** [comment]
Fixed: https://github.com/Dynatrace/Dynatrace-Config-Manager/releases/latest
