### ISSUE TITLE
Alert profiles still not populating management zones

### ISSUE THREAD

**Issue by jmclaugh04** [Dynatrace/Dynatrace-Config-Manager#120]
Issue still seems to exist with 1.4.12. Neither updating an existing configuration nor adding a new configuration applies the management zone to the alert profile. Export shows the management zone with proper ID in SaaS but never gets applied to the configuration.

**Comment by dcryans** [comment]
I'm sorry about that

Did you re-run "Execute OneTopology & TerraComposer" using the new version?
To re-create the tf files with the new code change

And then in the alerting module, in your .tf files, do you see something like this?
management_zone = "${var.dynatrace_management_zone_v2_MZ_NAME.value.id}"

**Comment by jmclaugh04** [comment]
Yes. Re ran the whole extract including execute OneTopology and terracomposer. Still failed to include the management zone.

**Comment by dcryans** [comment]
I would need to see the logs and your .tf files to understand better why it doesn't work

Just to make sure, you are running on either linux or windows, right?
I will soon update darwin (Apple Silicon), but it is very out of date v1.3.1

Can you open a support ticket with your files please?
from the tool: 
data/work/#-#/
- history/complete/<latest>/*.log
- config/modules/alerting/aaa.tf  <-- the alerting profile that is missing a management zone variable
- config/modules/management_zone_v2/bbb.tf   <--- the management zone that you expected to see in the alerting profile

Make sure you name me, David Cryans, so they assign the ticket to me directly


Thank you!

**Comment by dcryans** [comment]
Fixed temporarily in v1.4.14
Waiting for real fix from the Setting 2.0 Devs

https://github.com/Dynatrace/Dynatrace-Config-Manager/releases/latest

**Comment by dcryans** [comment]
This is now completely fixed
