### ISSUE TITLE
Publish the one-topology in the monaco repo

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-Config-Manager#87]
Hi!

I see from the output of the one-topology that it, in essence is monaco with some featureflags added (download entities among them)
Any plans on publishing this in the main monaco repo?

**Comment by dcryans** [comment]
it will be the opposite at some point, will extract the code to this repo or to the terraform provider repo

download entities was pushed to the Monaco repo in the past, but they removed it at some point

do you plan to use it for other purposes?

**Comment by dcryans** [comment]
This branch represents One-Topology, complete with extra APIs and added entity/config matching

https://github.com/dcryans/dynatrace-configuration-as-code/tree/feat/dcryans/match_entities_cmd

**Comment by dcryans** [comment]
Migrated One-Topology to this repo
the Fork will be deleted
