### ISSUE TITLE
Unsupported block type "lifecycle" for several modules in "plan and review" phase

### ISSUE THREAD

**Issue by sanitec** [Dynatrace/Dynatrace-Config-Manager#89]
**Describe the bug**
When I try running the step for "Plan all and review" it seems the tool suddenly stops. I can see in the console the following line is logged:
"127.0.0.1 - - [11/Jan/2024 14:55:25] "POST /terraform_history_configs?tenant_key_main=0&tenant_key_target=1 HTTP/1.1" 200 -
The command cd /home/stian/src/dnb/test-dt-config-mgr/data/work/0-1/terraform/config
terraform plan -lock=false -parallelism=10 -out=./2024-01-11_14-55-25_complete.plan >NUL > /home/stian/src/dnb/test-dt-config-mgr/data/work/0-1/terraform/history/complete/2024-01-11_14-55-25/2024-01-11_14-55-25_plan_all.log 2>&1 failed with error code 1
Deleting old overall directory:  /home/stian/src/dnb/test-dt-config-mgr/data/work/0-1/overall"

Out of curiosity I tried running the command, manually and I see multiple errors like:
"╷
│ Error: Unsupported block type
│
│   on modules/aws_credentials/AWS-CB-Migration-Dev_REGIONS_eu-west-1.aws_credentials.tf line 10, in resource "dynatrace_aws_credentials" "AWS-CB-Migration-Dev_REGIONS_eu-west-1":
│   10:     lifecycle {
│
│ Blocks of type "lifecycle" are not expected here.
╵
"

**Screenshots**
![image](https://github.com/Dynatrace/Dynatrace-Config-Manager/assets/2684572/eeb8f31b-70e5-43b5-abaf-9960966c339f)

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu 20.04
 - Browser: Edge (chromium)
 - Version 1.1.0

**Comment by dcryans** [comment]
Sorry about this, webhook fixed in version v1.1.2
Will look into aws credentials which is similar early next week

**Comment by dcryans** [comment]
Completely fixed with v1.1.3
https://github.com/Dynatrace/Dynatrace-Config-Manager/releases/latest
