### ISSUE TITLE
Bump terraform provider to newer than 1.8.3

### ISSUE THREAD

**Issue by tutnes** [Dynatrace/Dynatrace-Config-Manager#91]
**Is your feature request related to a problem? Please describe.**
Hi! Can you please bump the terraform provider to the newest version?

**Comment by dcryans** [comment]
it is almost latest version 1.8.3 is the number we use for Dev builds
I have planned to merge my code into the main branch at this quarter, but not done yet
In the meantime:
https://github.com/dynatrace-oss/terraform-provider-dynatrace/tree/feat/add_env_var_options_for_DT_CONF_MAN

Did you need to modify it?

**Comment by tutnes** [comment]
Hi! 

We have a fork where I have bumped it to 1.48.1:
https://github.com/kanari-com/Dynatrace-Config-Manager

**Comment by dcryans** [comment]
So you would like more transparency about the version my local branch is based on?

**Comment by tutnes** [comment]
Hi I see that you have bumped terraform provider to 1.50.0 now. thank you :)
